### PR TITLE
Add frontend

### PR DESCRIPTION
**Pull request by javepaid**
Jira ticket: https://lipsumtext.atlassian.net/browse/LS-6

Unit tests development still in progress. Suggestions are highly encouraged.

### CODE REVIEW

**Comment by javepaid** [comment]
Opened PR for review as per the request of the reviewer.

**Comment by javepaid** [comment]
Unit tests have finally been added. Please feel free to delete branch once PR is approved.

**Review by silikeite — APPROVED** [review]
Looks good. Merging is priority to get the chai fix in main.

**Comment by silikeite** [comment]
Not deleting branch for now pending discussion.

**Pull request merged**
